version: '3'

services:
  prestashop:
    image: oleiks/be_188612:latest
    container_name: prestashop
    ports:
      - "18861:443"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 60s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    command: sh -c './init.sh'
    networks:
      - admin-mysql_default
networks:
  admin-mysql_default:
    external: true